version: '3.8'

name: leftovers-backend

services:
  db:
    image: postgres:16.3
    container_name: leftovers-postgres
    restart: always
    ports:
      - 5555:5432
    env_file:
      - ".env"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  postgres:
    name: leftovers-postgress-db